### ISSUE TITLE
Feature suggestion: post-processing

### ISSUE THREAD

**Issue by strauhmanis** [alienator88/Viz#1]
_Hello Alin,_

Please consider adding a post-processing section to the app where users can instruct the app to execute system commands. For instance, the command `pbpaste | say` that would do the following:

- `pbpaste` is a command that retrieves the contents of the clipboard.
- `|` is the pipe symbol, which passes the output of the previous command as input to the next command.
- `say` is the command to make the system voice read aloud the provided text.

I suppose there are other useful functions that post-processing may allow, which is why I suggest not just adding a feature to voice-pronounce OCRed text, but rather implementing a post-processing section.

_Thank you_

**Comment by alienator88** [comment]
Hey!

That’s a cool idea. To confirm I understand, would this satisfy the requirement?
I could add a textfield where you can enter any shell command/s, including pipes, ampersands and semicolon command separators. 
If that field is not empty, execute the commands after the snip is taken. If there are no commands in the field, ignore and perform no post processing. 
Could also have a {content} token made available to add to the commands so the snipped content can be used in the shell commands directly. 
Example: 'say {content}'
This would then read aloud the content. 
Or: '{content} >> saved.txt'
To save the content to a local file.

Would this type of setup work?

-alin

**Comment by strauhmanis** [comment]
_Hello Alin,_

Indeed, that is the idea I had in mind.

The execution of this concept can go even further, I suppose, if you may be so inclined — Viz could pop-up notifications with the output of a shell command. For example, the command `pbpaste | wc -w` counts the number of words in clipboard and outputs that number in a numerical representation, which Viz then could display in the standard macOS notification message.

_Thank you_

**Comment by alienator88** [comment]
Okay, I think I can make that work. I'll play around with it for the next update.

**Comment by alienator88** [comment]
This has been released in v1.3
