### ISSUE TITLE
Translating Viz into Slovak

### ISSUE THREAD

**Issue by Svec-Tomas** [alienator88/Viz#4]
As a native Slovak speaker, I'd be happy to help you translate your app.

Please let me know if you'd be interested in my contribution.

Thanks!

**Comment by alienator88** [comment]
Hey @Svec-Tomas, I'm going to close this for now.
Once this repo gets active with more users, I'll definitely look to contextualize it to other languages.
For now though, it would be more work than it's worth for the time being.
I'll tag you when I get to that point though for sure.

P.S. Thanks for your help on Pearcleaner 🚀
