### ISSUE TITLE
[FR] Add mute sound option

### ISSUE THREAD

**Issue by Handwork5615** [alienator88/Viz#5]
If possible, please add option to mute sound.

**Comment by alienator88** [comment]
Good idea, I'll work on adding a setting to control the sound effect. 

As a workaround, you might be able to fix this yourself if you want until I add a setting.

Right click the app, view the Contents and look in the Resources folder. There should be a `printscreen.mp3` file there. Rename the file to something like `printscreen.mp3.bak` and restart the app. 
It should fail to find the file now when it tries to play it. 
I'm not sure if the app would crash though, so you could just test it out.

**Comment by Handwork5615** [comment]
It worked. Thanks so much 🙌🏼

**Comment by alienator88** [comment]
Added this option in latest release.
Thanks!
