### ISSUE TITLE
FEATURE REQUEST: OPTION TO REMOVE POPUP WINDOW

### ISSUE THREAD

**Issue by philocalyst** [alienator88/Viz#7]
Hey! Recently downloaded this, so forgive me if I'm missing something, but was wondering if there could be an option to disable the clipboard popup? It would fit nicely in the "Hide capture window" dropdown I feel. 

Just matches how I want my mac to feel better.

**Comment by alienator88** [comment]
I think that setting got messed up after I added the time dropdown. I just changed the logic to it so now if you toggle it off, it won't show the capture window at all. Then when you toggle it on, it will show the capture window for the set amount of time.
I just pushed the update out, let me know if that works for you!

**Comment by alienator88** [comment]
Yep it was something stupid lol..just missed a variable check for the processing window.
I updated the release with the newly fixed build if you want to re-download v1.8 again.
